### ISSUE TITLE
Slicing hangs

### ISSUE THREAD

**Issue by scsammyk** [Garr-R/OctoPrint-Slicer#6]
Thank you so much for developing this plugin. 

I've exported a profile from PrusaSlicer and imported it into Internal Slicer but I'm having trouble slicing. When I put in a model and chose slice it never finishes slicing. I've tried playing with the settings in PrusaSlicer just in case it was something I did there but even the most basic profile seems to fail. Sometimes it tells me the following error but most of the time I have to restart Octoprint to stop it from slicing. 

Slicing failed
{
"error": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
}

this is the output of the Octoprint log:

2024-04-27 00:06:31,293 - octoprint - ERROR - Exception on /api/files/local/3DP Camera Mount.tmp.1714190791010.stl [POST]
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/util/flask.py", line 1645, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/files.py", line 1076, in gcodeFileCommand
    fileManager.slice(
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/filemanager/__init__.py", line 534, in slice
    self._slicing_manager.cancel_slicing(
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/slicing/__init__.py", line 402, in cancel_slicing
    slicer.cancel_slicing(dest_path)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
TypeError: cancel_slicing() takes 1 positional argument but 2 were given

I also thought it might be overloading the CPU but I can't figure out how install the CPU limit as you have in the settings dialog. "Installing CPU Limitsudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required"

**Comment by Garr-Garr** [comment]
Please send your OctoPrint and internal slicer log files
